# anxt/HIDSensor.py
#  pyNXT - Python wrappers for aNXT
#  Copyright (C) 2010  Janosch Gräf
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from .I2C import DEFAULT_I2C_ADDR
from .Libanxt import Libanxt
from .Sensor import DEFAULT_DIGITAL_PORT, DigitalSensor
from ctypes import c_char_p


class HIDSensor(DigitalSensor):
    hidmodes = {"ASCII": 0x41,
             "DIRECT": 0x44}
    modifiers = {"NONE":       0x00,
                 None:         0x00,
                 "LEFTCTRL":   0x01,
                 "LEFTSHIFT":  0x02,
                 "LEFTALT":    0x04,
                 "LEFTGUI":    0x08,
                 "RIGHTCTRL":  0x10,
                 "RIGHTSHIFT": 0x20,
                 "RIGHTALT":   0x40,
                 "RIGHTGUI":   0x80}
    keys = {"NOEVENT":             0x00,
            "ERROVERUN":           0x01,
            "POSTFAIL":            0x02,
            "ERRUNDEF":            0x03,
            "A":                   0x04,
            "B":                   0x05,
            "C":                   0x06,
            "D":                   0x07,
            "E":                   0x08,
            "F":                   0x09,
            "G":                   0x0A,
            "H":                   0x0B,
            "I":                   0x0C,
            "J":                   0x0D,
            "K":                   0x0E,
            "L":                   0x0F,
            "M":                   0x10,
            "N":                   0x11,
            "O":                   0x12,
            "P":                   0x13,
            "Q":                   0x14,
            "R":                   0x15,
            "S":                   0x16,
            "T":                   0x17,
            "U":                   0x18,
            "V":                   0x19,
            "W":                   0x1A,
            "X":                   0x1B,
            "Y":                   0x1C,
            "Z":                   0x1D,
            "1":                   0x1E,
            "EXCLAIM":             0x1E,
            "2":                   0x1F,
            "AT":                  0x1F,
            "3":                   0x20,
            "HASH":                0x20,
            "4":                   0x21,
            "DOLLAR":              0x21,
            "5":                   0x22,
            "PERCENT":             0x22,
            "6":                   0x23,
            "CARET":               0x23,
            "7":                   0x24,
            "AMPERSAND":           0x24,
            "8":                   0x25,
            "ASTERISK":            0x25,
            "9":                   0x26,
            "LEFTPAREN":           0x26,
            "0":                   0x27,
            "RIGHTPAREN":          0x27,
            "RETURN":              0x28,
            "ESCAPE":              0x29,
            "BACKSPACE":           0x2A,
            "TAB":                 0x2B,
            "SPACE":               0x2C,
            "MINUS":               0x2D,
            "UNDERBAR":            0x2D,
            "EQUAL":               0x2E,
            "PLUS":                0x2E,
            "LEFTBRACKET":         0x2F,
            "LEFTBRACE":           0x2F,
            "RIGHTBRACKET":        0x30,
            "RIGHTBRACE":          0x30,
            "BACKSLASH":           0x31,
            "PIPE":                0x31,
            "EUROPE1":             0x32,
            "SEMICOLON":           0x33,
            "COLON":               0x33,
            "QUOTE":               0x34,
            "DOUBLEQUOTE":         0x34,
            "APOSTROPHE":          0x35,
            "TILDE":               0x35,
            "COMMA":               0x36,
            "LESS":                0x36,
            "PERIOD":              0x37,
            "GREATER":             0x37,
            "SLASH":               0x38,
            "QUESTION":            0x38,
            "CAPSLOCK":            0x39,
            "F1":                  0x3A,
            "F2":                  0x3B,
            "F3":                  0x3C,
            "F4":                  0x3D,
            "F5":                  0x3E,
            "F6":                  0x3F,
            "F7":                  0x40,
            "F8":                  0x41,
            "F9":                  0x42,
            "F10":                 0x43,
            "F11":                 0x44,
            "F12":                 0x45,
            "PRINTSCREEN":         0x46,
            "SCROLLLOCK":          0x47,
            "BREAK":               0x48,
            "PAUSE":               0x48,
            "INSERT":              0x49,
            "HOME":                0x4A,
            "PAGEUP":              0x4B,
            "DELETE":              0x4C,
            "END":                 0x4D,
            "PAGEDOWN":            0x4E,
            "RIGHT":               0x4F,
            "LEFT":                0x50,
            "DOWN":                0x51,
            "UP":                  0x52,
            "NUMLOCK":             0x53,
            "KEYPAD_SLASH":        0x54,
            "KEYPAD_ASTERISK":     0x55,
            "KEYPAD_MINUS":        0x56,
            "KEYPAD_PLUS":         0x57,
            "KEYPAD_ENTER":        0x58,
            "KEYPAD_1":            0x59,
            "KEYPAD_END":          0x59,
            "KEYPAD_2":            0x5A,
            "KEYPAD_DOWN":         0x5A,
            "KEYPAD_3":            0x5B,
            "KEYPAD_PAGEDOWN":     0x5B,
            "KEYPAD_4":            0x5C,
            "KEYPAD_LEFT":         0x5C,
            "KEYPAD_5":            0x5D,
            "KEYPAD_6":            0x5E,
            "KEYPAD_RIGHT":        0x5E,
            "KEYPAD_7":            0x5F,
            "KEYPAD_HOME":         0x5F,
            "KEYPAD_8":            0x60,
            "KEYPAD_UP":           0x60,
            "KEYPAD_9":            0x61,
            "KEYPAD_PAGEUP":       0x61,
            "KEYPAD_0":            0x62,
            "KEYPAD_INSERT":       0x62,
            "KEYPAD_PERIOD":       0x63,
            "KEYPAD_DELETE":       0x63,
            "EUROPE2":             0x64,
            "APP":                 0x65,
            "KEYBOARD_POWER":      0x66,
            "KEYPAD_EQUAL":        0x67,
            "F13":                 0x68,
            "F14":                 0x68,
            "F15":                 0x6A,
            "F16":                 0x6B,
            "F17":                 0x6C,
            "F18":                 0x6D,
            "F19":                 0x6E,
            "F20":                 0x6F,
            "F21":                 0x70,
            "F22":                 0x71,
            "F23":                 0x72,
            "F24":                 0x73,
            "KEYBOARD_EXEC":       0x74,
            "KEYBOARD_HELP":       0x75,
            "KEYBOARD_MENU":       0x76,
            "KEYBOARD_SELECT":     0x77,
            "KEYBOARD_STOP":       0x78,
            "KEYBOARD_AGAIN":      0x79,
            "KEYBOARD_UNDO":       0x7A,
            "KEYBOARD_CUT":        0x7B,
            "KEYBOARD_COPY":       0x7C,
            "KEYBOARD_PASTE":      0x7D,
            "KEYBOARD_FIND":       0x7E,
            "KEYBOARD_MUTE":       0x7F,
            "KEYBOARD_VOLUP":      0x80,
            "KEYBOARD_VOLDOWN":    0x81,
            "KEYBOARD_CAPSLOCK":   0x82,
            "KEYBOARD_NUMLOCK":    0x83,
            "KEYBOARD_SCROLLLOCK": 0x84,
            "KEYPAD_COMMA":        0x85,
            "KEYBOARD_EQUAL":      0x86,
            "KEYBOARD_INTL1":      0x87,
            "KEYBOARD_INTL2":      0x88,
            "KEYBOARD_INTL3":      0x89,
            "KEYBOARD_INTL4":      0x8A,
            "KEYBOARD_INTL5":      0x8B,
            "KEYBOARD_INTL6":      0x8C,
            "KEYBOARD_INTL7":      0x8D,
            "KEYBOARD_INTL8":      0x8E,
            "KEYBOARD_INTL9":      0x8F,
            "KEYBOARD_LANG1":      0x90,
            "KEYBOARD_LANG2":      0x91,
            "KEYBOARD_LANG3":      0x92,
            "KEYBOARD_LANG4":      0x93,
            "KEYBOARD_LANG5":      0x94,
            "KEYBOARD_LANG6":      0x95,
            "KEYBOARD_LANG7":      0x96,
            "KEYBOARD_LANG8":      0x97,
            "KEYBOARD_LANG9":      0x98,
            "KEYBOARD_ALT_EREASE": 0x99,
            "KEYBOARD_SYSREQ":     0x9A,
            "KEYBOARD_ATTENTION":  0x9A,
            "KEYBOARD_CANCEL":     0x9B,
            "KEYBOARD_CLEAR":      0x9C,
            "KEYBOARD_PRIOR":      0x9D,
            "KEYBOARD_RETURN":     0x9E,
            "KEYBOARD_SEPARATOR":  0x9F,
            "KEYBOARD_OUT":        0xA0,
            "KEYBOARD_OPER":       0xA1,
            "KEYBOARD_CLEAR2":     0xA2,
            "KEYBOARD_AGAIN2":     0xA2,
            "KEYBOARD_CRSEL":      0xA3,
            "KEYBOARD_PROPS":      0xA3,
            "KEYBOARD_EXSEL":      0xA4,
            "LEFTCONTROL":         0xE0,
            "LEFTSHIFT":           0xE1,
            "LEFTALT":             0xE2,
            "LEFTGUI":             0xE3,
            "RIGHTCONTROL":        0xE4,
            "RIGHTSHIFT":          0xE5,
            "RIGHTALT":            0xE6,
            "RIGHTGUI":            0xE7,
            "SYSPOWER":            0x81,
            "SYSSLEEP":            0x82,
            "SYSWAKE":             0x83}

    def __init__(self, nxt, port = DEFAULT_DIGITAL_PORT, i2c_addr = 0x04):
        DigitalSensor.__init__(self, nxt, port, i2c_addr)
        
    def set_modifier(self, modifier):
        self.set_addr_param("hid")
        return int(self.nxt.libanxt.nxt_hid_set_modifier(self.nxt.handle, self.port-1, self.modifiers[modifier]))==0

    def set_key(self, key, direct=True):
        self.set_addr_param("hid")
        if (direct):
            k = self.keys[key]
        else:
            k = ord(key)

        return int(self.nxt.libanxt.nxt_hid_set_key(self.nxt.handle, self.port-1, k))==0

    def transmit(self):
        self.set_addr_param("hid")
        return int(self.nxt.libanxt.nxt_hid_transmit(self.nxt.handle, self.port-1))==0

    def set_mode(self, mode = "ASCII"):
        self.set_addr_param("hid")
        return int(self.nxt.libanxt.nxt_hid_set_mode(self.nxt.handle, self.port-1, self.hidmodes[mode]))==0

    def send_str(self, text):
        self.set_addr_param("hid")
        return int(self.nxt.libanxt.nxt_hid_send_str(self.nxt.handle, self.port-1, c_char_p(text)))==0
